"""empty message

Revision ID: 9150792addf2
Revises: c8f5529acd25
Create Date: 2021-09-08 12:40:48.980674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, String

# revision identifiers, used by Alembic.
revision = '9150792addf2'
down_revision = 'c8f5529acd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games',
        Column('type', String())
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games',
        Column('type', String())
    )
    # ### end Alembic commands ###
